# Generated by Django 5.1.4 on 2026-08-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0007_create_django_cache_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoodEntry',
            new_name='JournalEntry',
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'verbose_name': 'JournalEntry', 'verbose_name_plural': 'JournalEntries'},
        ),
    ]
