# Generated by Django 5.1.4 on 2026-08-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0008_rename_moodentry_journalentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('mood_chat', 'Mood chat'), ('breathing', 'Breathing exercise'), ('sudoku', 'Sudoku'), ('drawing', 'Free drawing'), ('letter_read', 'Weekly letter read')], db_index=True, default='mood_chat', max_length=20),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='ai_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='emoji',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='thoughts',
            field=models.TextField(blank=True, default=''),
        ),
    ]
