# Generated by Django 5.1.4 on 2026-09-08 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0009_journalentry_entry_type_journalentry_payload_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_text', models.TextField()),
                ('user_message', models.TextField(blank=True, default='')),
                ('reason', models.CharField(choices=[('offensive_harmful', 'Offensive or harmful'), ('inaccurate', 'Inaccurate or unhelpful'), ('uncomfortable', 'Made me uncomfortable'), ('other', 'Other')], max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
