# Generated by Django 5.1.4 on 2026-07-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_preferred_language_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='memory_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='memory_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
